### ISSUE TITLE
$mdDialog scope

### ISSUE THREAD

**Issue by marvelsrp** [frankland/valentjs#15]
Нет возможности выполнить digest по модальному окну. 
1. Открывается $mdDialog.
2. Шаблон ожидает данные из api, отображается loader.
3. Данные пришли из ap, loader скрывается, но Digest.run(this) выдает ошибку, потому что контекста модального окна его нет в массиве scopes.

**Comment by marvelsrp** [comment]
Проверено на 1.0.121. Возможно в новых версиях уже пофикшено?

**Comment by bozheville** [comment]
+1
